### PR TITLE
implement opening dropdown by space pressing

### PR DESCRIPTION
**Pull request by stasiukanya**
This PR will allow opening dropdown by space pressing. Also, I've added the attribute `role="button"` to the dropdown wrapper to make it accessible by keyboard navigation tools like Vimium.

### CODE REVIEW

**Comment by stasiukanya** [comment]
Regarding the keyboard navigation. As you can see on the screenshot, the current version of the dropdown is not accessible by the keyboard navigation tool Vimium.

Screenshot 2020-07-30 at 16 18 20

I found `role="button"`  approach in Material-UI (they set this attribute for their dropdowns).

Thanks for your work on this project! :raised_hands:

**Comment by jfangrad** [comment]
Hey, @stasiukanya thanks for this PR!

The changes look good to me. The only thing that would be nice its to have tests for the space opening the dropdown if it's not searchable. And then another to make sure if it is searchable that it doesn't open with space. (Can look at other tests around opening/closing the dropdown)

If you are willing to add those in quick that would be great and we can merge this in. If not I could just add them in after.

**Comment by stasiukanya** [comment]
Thanks for merging! I'm not planning changes for now, so it would be great a release with just this🙂

**Comment by jfangrad** [comment]
@stasiukanya version 2.0.7 is out. Thanks again!

**Pull request merged**
